#!/bin/bash
# Quick guide to apply the Canva Business migration
# Since we can't execute SQL directly via API with anon key,
# follow these steps in your Supabase Dashboard

echo "════════════════════════════════════════════════════════════════"
echo "  🚀 Apply Canva Business Migration to Supabase"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Your Supabase Project: https://dqirldrlusrmodkwlnqy.supabase.co"
echo ""
echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://supabase.com/dashboard/project/dqirldrlusrmodkwlnqy/editor"
echo ""
echo "2. In the left sidebar, click 'SQL Editor'"
echo ""
echo "3. Click 'New Query' button (top right)"
echo ""
echo "4. Copy and paste this SQL:"
echo ""
echo "════════════════════════════════════════════════════════════════"
cat supabase/migrations/002_add_canva_business_type.sql
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "5. Click 'Run' button (or press Ctrl+Enter / Cmd+Enter)"
echo ""
echo "6. You should see: 'Success. No rows returned'"
echo ""
echo "✅ DONE! 'Canva Business' is now an allowed business type."
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🧪 Test the Migration"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Try creating a test business with type 'Canva Business':"
echo ""
echo "curl -X POST \\"
echo "  'https://dqirldrlusrmodkwlnqy.supabase.co/rest/v1/businesses' \\"
echo "  -H 'apikey: YOUR_ANON_KEY' \\"
echo "  -H 'Authorization: Bearer YOUR_ANON_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"Test Canva Business\",\"type\":\"Canva Business\",\"location\":\"Downtown Norfolk\"}'"
echo ""
echo "════════════════════════════════════════════════════════════════"
