name = "bettadayz-pbbg"
main = "cloudflare-worker.js"
compatibility_date = "2024-10-30"

[vars]
SERVER_IP = "194.195.84.72"
SHOP_PORT = "3000"
STORE_PORT = "3001"
JWT_SECRET = "9=N6H//qQ]?g+BDV"
WORKER_TOKEN = "after9b9fcaead55610e5dd235878e702ee69"
NODE_ENV = "production"

[build]
command = "npm run build"

[observability]
enabled = true