name = "bettadayz-pbbg"
main = "cloudflare-worker.js"
compatibility_date = "2023-12-01"

# Cloudflare Pages configuration for Next.js
# Static build output directory
pages_build_output_dir = "out"

[vars]
SERVER_IP = "194.195.84.72"
SHOP_PORT = "3000"
STORE_PORT = "3001"
JWT_SECRET = "9=N6H//qQ]?g+BDV"
WORKER_TOKEN = "after9b9fcaead55610e5dd235878e702ee69"
NODE_ENV = "production"
PRIMARY_DOMAIN = "bettadayz.shop"
SECONDARY_DOMAIN = "bettadayz.store"
NEXT_PUBLIC_SUPABASE_URL = "https://btcfpizydmcdjhltwbil.supabase.co"

[build]
command = "npm run build"
cwd = ""

# Custom domains for dual domain setup
[[route]]
pattern = "bettadayz.shop/*"
zone_name = "bettadayz.shop"

[[route]]
pattern = "bettadayz.store/*"
zone_name = "bettadayz.store"

[observability]
enabled = true