name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper subtree support

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all workspaces
        run: npm run build
        continue-on-error: true  # Allow build to continue if some workspaces fail

      - name: Run tests
        run: npm test
        continue-on-error: true  # Don't block PR if tests fail (no tests yet)

      - name: Lint
        run: npm run lint
        continue-on-error: true  # Don't block PR if linting fails
