name: Deploy docs to GitHub Pages

on:
  push:
    branches: [ main, fix/gh-pages-prepare ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare docs folder
        # The prepare script is a small Node script that copies nested docs into ./docs.
        # We avoid running a full `npm ci` here to keep the workflow fast and resilient.
        run: node scripts/prepare-gh_pages.cjs

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
